export const attacks = [
  { type: "grass", name: "Absorb", power: 20 },
  { type: "poison", name: "Acid", power: 40 },
  { type: "poison", name: "Acid Armor", power: 1 },
  { type: "psychic", name: "Agility", power: 1 },
  { type: "psychic", name: "Amnesia", power: 1 },
  { type: "ice", name: "Aurora Beam", power: 65 },
  { type: "normal", name: "Barrage", power: 15 },
  { type: "psychic", name: "Barrier", power: 1 },
  { type: "normal", name: "Bide", power: 1 },
  { type: "normal", name: "Bind", power: 15 },
  { type: "dark", name: "Bite", power: 60 },
  { type: "ice", name: "Blizzard", power: 110 },
  { type: "normal", name: "Body Slam", power: 85 },
  { type: "ground", name: "Bone Club", power: 65 },
  { type: "ground", name: "Boomerang", power: 50 },
  { type: "water", name: "Bubble", power: 40 },
  { type: "water", name: "Bubble Beam", power: 65 },
  { type: "water", name: "Clamp", power: 35 },
  { type: "normal", name: "Comet Punch", power: 18 },
  { type: "ghost", name: "Confuse Ray", power: 1 },
  { type: "psychic", name: "Confusion", power: 50 },
  { type: "normal", name: "Constrict", power: 10 },
  { type: "normal", name: "Conversion", power: 1 },
  { type: "fighting", name: "Counter", power: 1 },
  { type: "water", name: "Crabhammer", power: 100 },
  { type: "normal", name: "Cut", power: 50 },
  { type: "normal", name: "Defense Curl", power: 1 },
  { type: "ground", name: "Dig", power: 80 },
  { type: "normal", name: "Disable", power: 1 },
  { type: "normal", name: "Dizzy Punch", power: 70 },
  { type: "fighting", name: "Double Kick", power: 30 },
  { type: "normal", name: "Double Slap", power: 15 },
  { type: "normal", name: "Double Team", power: 1 },
  { type: "normal", name: "Double-Edge", power: 120 },
  { type: "dragon", name: "Dragon Rage", power: 1 },
  { type: "psychic", name: "Dream Eater", power: 100 },
  { type: "flying", name: "Drill Peck", power: 80 },
  { type: "ground", name: "Earthquake", power: 100 },
  { type: "normal", name: "Egg Bomb", power: 100 },
  { type: "fire", name: "Ember", power: 40 },
  { type: "normal", name: "Explosion", power: 250 },
  { type: "fire", name: "Fire Blast", power: 110 },
  { type: "fire", name: "Fire Punch", power: 75 },
  { type: "fire", name: "Fire Spin", power: 15 },
  { type: "ground", name: "Fissure", power: 1 },
  { type: "fire", name: "Flamethrower", power: 90 },
  { type: "normal", name: "Flash", power: 1 },
  { type: "flying", name: "Fly", power: 90 },
  { type: "normal", name: "Focus Energy", power: 1 },
  { type: "normal", name: "Fury Attack", power: 15 },
  { type: "normal", name: "Fury Swipes", power: 18 },
  { type: "normal", name: "Glare", power: 1 },
  { type: "normal", name: "Growl", power: 1 },
  { type: "normal", name: "Growth", power: 1 },
  { type: "normal", name: "Guillotine", power: 1 },
  { type: "flying", name: "Gust", power: 40 },
  { type: "normal", name: "Harden", power: 1 },
  { type: "ice", name: "Haze", power: 1 },
  { type: "normal", name: "Headbutt", power: 70 },
  { type: "fighting", name: "High Jump Kick", power: 130 },
  { type: "normal", name: "Horn Attack", power: 65 },
  { type: "normal", name: "Horn Drill", power: 1 },
  { type: "water", name: "Hydro Pump", power: 110 },
  { type: "normal", name: "Hyper Beam", power: 150 },
  { type: "normal", name: "Hyper Fang", power: 80 },
  { type: "psychic", name: "Hypnosis", power: 1 },
  { type: "ice", name: "Ice Beam", power: 90 },
  { type: "ice", name: "Ice Punch", power: 75 },
  { type: "fighting", name: "Jump Kick", power: 100 },
  { type: "fighting", name: "Karate Chop", power: 50 },
  { type: "psychic", name: "Kinesis", power: 1 },
  { type: "bug", name: "Leech Life", power: 80 },
  { type: "grass", name: "Leech Seed", power: 1 },
  { type: "normal", name: "Leer", power: 1 },
  { type: "ghost", name: "Lick", power: 30 },
  { type: "psychic", name: "Light-screen", power: 1 },
  { type: "fighting", name: "Low Kick", power: 1 },
  { type: "normal", name: "Lovely Kiss", power: 1 },
  { type: "psychic", name: "Meditate", power: 1 },
  { type: "grass", name: "Mega Drain", power: 40 },
  { type: "normal", name: "Mega Kick", power: 120 },
  { type: "normal", name: "Mega Punch", power: 80 },
  { type: "normal", name: "Metronome", power: 1 },
  { type: "normal", name: "Mimic", power: 1 },
  { type: "normal", name: "Minimize", power: 1 },
  { type: "flying", name: "Mirror Move", power: 1 },
  { type: "ice", name: "Mist", power: 1 },
  { type: "ghost", name: "Night Shade", power: 1 },
  { type: "normal", name: "Pay Day", power: 40 },
  { type: "flying", name: "Peck", power: 35 },
  { type: "grass", name: "Petal Dance", power: 120 },
  { type: "bug", name: "Pin Missile", power: 25 },
  { type: "poison", name: "Poison Gas", power: 1 },
  { type: "poison", name: "Poison Sting", power: 15 },
  { type: "poison", name: "Poison Powder", power: 1 },
  { type: "normal", name: "Pound", power: 40 },
  { type: "psychic", name: "Psybeam", power: 65 },
  { type: "psychic", name: "Psychic", power: 90 },
  { type: "psychic", name: "Psywave", power: 1 },
  { type: "normal", name: "Quick Attack", power: 40 },
  { type: "normal", name: "Rage", power: 20 },
  { type: "grass", name: "Razor Leaf", power: 55 },
  { type: "normal", name: "Razor Wind", power: 80 },
  { type: "normal", name: "Recover", power: 1 },
  { type: "psychic", name: "Reflect", power: 1 },
  { type: "psychic", name: "Rest", power: 1 },
  { type: "normal", name: "Roar", power: 1 },
  { type: "rock", name: "Rock Slide", power: 75 },
  { type: "rock", name: "Rock Throw", power: 50 },
  { type: "fighting", name: "Rolling Kick", power: 60 },
  { type: "ground", name: "Sand Attack", power: 1 },
  { type: "normal", name: "Scratch", power: 40 },
  { type: "normal", name: "Screech", power: 1 },
  { type: "fighting", name: "Seismic Toss", power: 1 },
  { type: "normal", name: "Self-Destruct", power: 200 },
  { type: "normal", name: "Sharpen", power: 1 },
  { type: "normal", name: "Sing", power: 1 },
  { type: "normal", name: "Skull Bash", power: 130 },
  { type: "flying", name: "Sky Attack", power: 140 },
  { type: "normal", name: "Slam", power: 80 },
  { type: "normal", name: "Slash", power: 70 },
  { type: "grass", name: "Sleep Powder", power: 1 },
  { type: "poison", name: "Sludge", power: 65 },
  { type: "poison", name: "Smog", power: 30 },
  { type: "normal", name: "Smokescreen", power: 1 },
  { type: "normal", name: "Soft-Boiled", power: 1 },
  { type: "normal", name: "Sonic Boom", power: 1 },
  { type: "grass", name: "Solar Beam", power: 120 },
  { type: "normal", name: "Spike Cannon", power: 20 },
  { type: "normal", name: "Splash", power: 1 },
  { type: "Grass", name: "Spore", power: 1 },
  { type: "normal", name: "Stomp", power: 65 },
  { type: "normal", name: "Strength", power: 80 },
  { type: "normal", name: "Struggle", power: 50 },
  { type: "bug", name: "String Shot", power: 1 },
  { type: "grass", name: "Stun Spore", power: 1 },
  { type: "fighting", name: "Submission", power: 80 },
  { type: "normal", name: "Substitute", power: 1 },
  { type: "normal", name: "Super Fang", power: 1 },
  { type: "normal", name: "Supersonic", power: 1 },
  { type: "water", name: "Surf", power: 90 },
  { type: "normal", name: "Swift", power: 60 },
  { type: "normal", name: "Swords Dance", power: 1 },
  { type: "normal", name: "Tackle", power: 40 },
  { type: "normal", name: "Tail Whip", power: 1 },
  { type: "normal", name: "Take Down", power: 90 },
  { type: "psychic", name: "Teleport", power: 1 },
  { type: "normal", name: "Thrash", power: 120 },
  { type: "eletric", name: "Thunder", power: 110 },
  { type: "eletric", name: "Thunder Wave", power: 1 },
  { type: "eletric", name: "Thunderbolt", power: 90 },
  { type: "eletric", name: "Thunder Punch", power: 75 },
  { type: "eletric", name: "Thunder Shock", power: 40 },
  { type: "poison", name: "Toxic", power: 1 },
  { type: "normal", name: "Transform", power: 1 },
  { type: "normal", name: "Tri Attack", power: 80 },
  { type: "bug", name: "Twineedle", power: 25 },
  { type: "grass", name: "Vine Whip", power: 45 },
  { type: "normal", name: "Vise Grip", power: 55 },
  { type: "water", name: "Water Gun", power: 40 },
  { type: "water", name: "Waterfall", power: 80 },
  { type: "normal", name: "Whirlwind", power: 1 },
  { type: "flying", name: "Wing Attack", power: 60 },
  { type: "water", name: "Withdraw", power: 1 },
  { type: "normal", name: "Wrap", power: 1 },
];
