export const pokemons = [
  {
    id: 1,
    name: "Bulbasaur",
    type: "grass",
    level: 5,
    hp: 45,
    moves: ["Tackle", "Leech Seed", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/1.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/1.png",
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "grass",
    level: 16,
    hp: 60,
    moves: ["Body Slam", "Double Team", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/2.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/2.png",
  },
  {
    id: 3,
    name: "Venusaur",
    type: "grass",
    level: 36,
    hp: 80,
    moves: ["Body Slam", "Mega Drain", "Razor Leaf", "Solar Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/3.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/3.png",
  },
  {
    id: 4,
    name: "Charmander",
    type: "fire",
    level: 5,
    hp: 39,
    moves: ["Scratch", "Growl", "Ember", "Smokescreen"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/4.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/4.png",
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "fire",
    level: 16,
    hp: 58,
    moves: ["Slash", "Rage", "Ember", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/5.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/5.png",
  },
  {
    id: 6,
    name: "Charizard",
    type: "fire",
    level: 36,
    hp: 78,
    moves: ["Slash", "Fly", "Earthquake", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/6.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/6.png",
  },
  {
    id: 7,
    name: "Squirtle",
    type: "water",
    level: 5,
    hp: 44,
    moves: ["Tackle", "Bite", "Water Gun", "Bubble"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/7.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/7.png",
  },
  {
    id: 8,
    name: "Wartortle",
    type: "water",
    level: 16,
    hp: 59,
    moves: ["Bite", "Skull Bash", "Body Slam", "Bubblebeam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/8.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/8.png",
  },
  {
    id: 9,
    name: "Blastoise",
    type: "water",
    level: 36,
    hp: 79,
    moves: ["Double Edge", "Ice Beam", "Earthquake", "Surf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/9.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/9.png",
  },
  {
    id: 10,
    name: "Caterpie",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Tackle", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/10.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/10.png",
  },
  {
    id: 11,
    name: "Metapod",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/11.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/11.png",
  },
  {
    id: 12,
    name: "Butterfree",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Toxic", "Sleep Powder", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/12.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/12.png",
  },
  {
    id: 13,
    name: "Weedle",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Poison Sting", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/13.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/13.png",
  },
  {
    id: 14,
    name: "Kakuna",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/14.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/14.png",
  },
  {
    id: 15,
    name: "Beedrill",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Fury Attack", "Swords Dance", "Toxic", "Double Edge"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/15.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/15.png",
  },
  {
    id: 16,
    name: "Pidgey",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Gust", "Quick Attack", "Sand Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/16.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/16.png",
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: "normal",
    level: 16,
    hp: 63,
    moves: ["Take Down", "Razor Wind", "Double Team", "Sky Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/17.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/17.png",
  },
  {
    id: 18,
    name: "Pidgeot",
    type: "normal",
    level: 36,
    hp: 83,
    moves: ["Double Edge", "Wing Attack", "Double Team", "Fly"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/18.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/18.png",
  },

  {
    id: 19,
    name: "Rattata",
    type: "normal",
    level: 5,
    hp: 30,
    moves: ["Tackle", "Quick Attack", "Focus Energy"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/19.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/19.png",
  },
  {
    id: 20,
    name: "Raticate",
    type: "normal",
    level: 16,
    hp: 55,
    moves: ["Bite", "Hyper Fang", "Quick Attack", "Focus Energy"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/20.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/20.png",
  },
  {
    id: 21,
    name: "Spearow",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Gust", "Peck", "Quick Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/21.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/21.png",
  },
  {
    id: 22,
    name: "Fearow",
    type: "normal",
    level: 16,
    hp: 65,
    moves: ["Drill Peck", "Aerial Ace", "Quick Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/22.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/22.png",
  },
  {
    id: 23,
    name: "Ekans",
    type: "poison",
    level: 5,
    hp: 35,
    moves: ["Poison Sting", "Wrap", "Acid"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/23.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/23.png",
  },
  {
    id: 24,
    name: "Arbok",
    type: "poison",
    level: 16,
    hp: 60,
    moves: ["Bite", "Wrap", "Acid", "Glare"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/24.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/24.png",
  },
  {
    id: 25,
    name: "Pikachu",
    type: "electric",
    level: 5,
    hp: 35,
    moves: ["Thunder Shock", "Quick Attack", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/25.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/25.png",
  },
  {
    id: 26,
    name: "Raichu",
    type: "electric",
    level: 16,
    hp: 60,
    moves: ["Thunder Shock", "Quick Attack", "Thunder", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/26.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/26.png",
  },
  {
    id: 27,
    name: "Sandshrew",
    type: "ground",
    level: 5,
    hp: 50,
    moves: ["Scratch", "Sand Attack", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/27.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/27.png",
  },
  {
    id: 28,
    name: "Sandslash",
    type: "ground",
    level: 16,
    hp: 75,
    moves: ["Scratch", "Sand Attack", "Slash", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/28.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/28.png",
  },
  {
    id: 29,
    name: "Nidoran♀",
    type: "poison",
    level: 5,
    hp: 55,
    moves: ["Poison Sting", "Scratch", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/29.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/29.png",
  },
  {
    id: 30,
    name: "Nidorina",
    type: "poison",
    level: 16,
    hp: 70,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/30.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/30.png",
  },
  {
    id: 31,
    name: "Nidoqueen",
    type: "poison",
    level: 36,
    hp: 90,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/31.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/31.png",
  },
  {
    id: 32,
    name: "Nidoran♂",
    type: "poison",
    level: 5,
    hp: 46,
    moves: ["Poison Sting", "Scratch", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/32.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/32.png",
  },
  {
    id: 33,
    name: "Nidorino",
    type: "poison",
    level: 16,
    hp: 61,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/33.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/33.png",
  },
  {
    id: 34,
    name: "Nidoking",
    type: "poison",
    level: 36,
    hp: 81,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/34.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/34.png",
  },
  {
    id: 35,
    name: "Clefairy",
    type: "fairy",
    level: 5,
    hp: 70,
    moves: ["Pound", "Sing", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/35.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/35.png",
  },
  {
    id: 36,
    name: "Clefable",
    type: "fairy",
    level: 16,
    hp: 95,
    moves: ["Pound", "Sing", "Defense Curl", "Moonblast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/36.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/36.png",
  },
  {
    id: 37,
    name: "Vulpix",
    type: "fire",
    level: 5,
    hp: 38,
    moves: ["Ember", "Quick Attack", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/37.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/37.png",
  },
  {
    id: 38,
    name: "Ninetales",
    type: "fire",
    level: 16,
    hp: 73,
    moves: ["Ember", "Quick Attack", "Tail Whip", "Fire Blast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/38.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/38.png",
  },
  {
    id: 39,
    name: "Jigglypuff",
    type: "normal",
    level: 5,
    hp: 115,
    moves: ["Pound", "Sing", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/39.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/39.png",
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: "normal",
    level: 16,
    hp: 140,
    moves: ["Pound", "Sing", "Defense Curl", "Dazzling Gleam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/40.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/40.png",
  },
  {
    id: 41,
    name: "Zubat",
    type: "poison",
    level: 5,
    hp: 40,
    moves: ["Bite", "Leer", "Quick Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/41.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/41.png",
  },
  {
    id: 42,
    name: "Golbat",
    type: "poison",
    level: 16,
    hp: 75,
    moves: ["Bite", "Leer", "Quick Attack", "Wing Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/42.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/42.png",
  },
  {
    id: 43,
    name: "Oddish",
    type: "grass",
    level: 5,
    hp: 45,
    moves: ["Absorb", "Poison Powder", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/43.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/43.png",
  },
  {
    id: 44,
    name: "Gloom",
    type: "grass",
    level: 16,
    hp: 60,
    moves: ["Absorb", "Poison Powder", "Sleep Powder", "Acid"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/44.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/44.png",
  },
  {
    id: 45,
    name: "Vileplume",
    type: "grass",
    level: 36,
    hp: 75,
    moves: ["Poison Powder", "Sleep Powder", "Acid", "Petal Dance"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/45.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/45.png",
  },
  {
    id: 46,
    name: "Paras",
    type: "bug",
    level: 5,
    hp: 35,
    moves: ["Scratch", "Stun Spore", "Poison Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/46.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/46.png",
  },
  {
    id: 47,
    name: "Parasect",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["Stun Spore", "Poison Powder", "Fury Cutter"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/47.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/47.png",
  },
  {
    id: 48,
    name: "Venonat",
    type: "bug",
    level: 5,
    hp: 60,
    moves: ["Confusion", "Poison Powder", "Stun Spore"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/48.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/48.png",
  },
  {
    id: 49,
    name: "Venomoth",
    type: "bug",
    level: 16,
    hp: 70,
    moves: ["Confusion", "Poison Powder", "Stun Spore", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/49.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/49.png",
  },
  {
    id: 50,
    name: "Diglett",
    type: "ground",
    level: 5,
    hp: 10,
    moves: ["Scratch", "Sand Attack", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/50.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/50.png",
  },
  {
    id: 51,
    name: "Dugtrio",
    type: "ground",
    level: 16,
    hp: 35,
    moves: ["Mud Slap", "Sand Attack", "Mud Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/51.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/51.png",
  },
  {
    id: 52,
    name: "Meowth",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Scratch", "Bite", "Quick Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/52.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/52.png",
  },
  {
    id: 53,
    name: "Persian",
    type: "normal",
    level: 16,
    hp: 65,
    moves: ["Scratch", "Bite", "Quick Attack", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/53.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/53.png",
  },
  {
    id: 54,
    name: "Psyduck",
    type: "water",
    level: 5,
    hp: 50,
    moves: ["Scratch", "Water Gun", "Zen Headbutt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/54.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/54.png",
  },
  {
    id: 55,
    name: "Golduck",
    type: "water",
    level: 16,
    hp: 80,
    moves: ["Scratch", "Water Gun", "Zen Headbutt", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/55.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/55.png",
  },
  {
    id: 56,
    name: "Mankey",
    type: "fighting",
    level: 5,
    hp: 40,
    moves: ["Scratch", "Low Kick", "Karate Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/56.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/56.png",
  },
  {
    id: 57,
    name: "Primeape",
    type: "fighting",
    level: 16,
    hp: 65,
    moves: ["Scratch", "Low Kick", "Karate Chop", "Cross Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/57.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/57.png",
  },
  {
    id: 58,
    name: "Growlithe",
    type: "fire",
    level: 5,
    hp: 55,
    moves: ["Bite", "Ember", "Odor Sleuth"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/58.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/58.png",
  },
  {
    id: 59,
    name: "Arcanine",
    type: "fire",
    level: 16,
    hp: 90,
    moves: ["Bite", "Ember", "Odor Sleuth", "Fire Fang"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/59.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/59.png",
  },
  {
    id: 60,
    name: "Poliwag",
    type: "water",
    level: 5,
    hp: 40,
    moves: ["Bubble", "Water Gun", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/60.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/60.png",
  },
  {
    id: 61,
    name: "Poliwhirl",
    type: "water",
    level: 16,
    hp: 65,
    moves: ["Bubble", "Water Gun", "Mud Slap", "Bubble Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/61.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/61.png",
  },
  {
    id: 62,
    name: "Poliwrath",
    type: "water",
    level: 36,
    hp: 90,
    moves: ["Water Gun", "Mud Slap", "Bubble Beam", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/62.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/62.png",
  },
  {
    id: 63,
    name: "Abra",
    type: "psychic",
    level: 5,
    hp: 25,
    moves: ["Teleport", "Zen Headbutt", "Confusion"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/63.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/63.png",
  },
  {
    id: 64,
    name: "Kadabra",
    type: "psychic",
    level: 16,
    hp: 40,
    moves: ["Teleport", "Zen Headbutt", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/64.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/64.png",
  },
  {
    id: 65,
    name: "Alakazam",
    type: "psychic",
    level: 36,
    hp: 55,
    moves: ["Teleport", "Zen Headbutt", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/65.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/65.png",
  },
  {
    id: 66,
    name: "Machop",
    type: "fighting",
    level: 5,
    hp: 40,
    moves: ["Low Kick", "Karate Chop", "Cross Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/66.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/66.png",
  },
  {
    id: 67,
    name: "Machoke",
    type: "fighting",
    level: 16,
    hp: 65,
    moves: ["Low Kick", "Karate Chop", "Cross Chop", "Submission"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/67.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/67.png",
  },
  {
    id: 68,
    name: "Machamp",
    type: "fighting",
    level: 36,
    hp: 90,
    moves: ["Low Kick", "Karate Chop", "Cross Chop", "Submission"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/68.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/68.png",
  },
  {
    id: 69,
    name: "Bellsprout",
    type: "grass",
    level: 5,
    hp: 50,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/69.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/69.png",
  },
  {
    id: 70,
    name: "Weepinbell",
    type: "grass",
    level: 16,
    hp: 65,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder", "Seed Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/70.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/70.png",
  },
  {
    id: 71,
    name: "Victreebel",
    type: "grass",
    level: 36,
    hp: 80,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder", "Seed Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/71.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/71.png",
  },
  {
    id: 72,
    name: "Tentacool",
    type: "water",
    level: 5,
    hp: 40,
    moves: ["Bubble", "Poison Sting", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/72.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/72.png",
  },
  {
    id: 73,
    name: "Tentacruel",
    type: "water",
    level: 16,
    hp: 80,
    moves: ["Bubble", "Poison Sting", "Water Gun", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/73.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/73.png",
  },
  {
    id: 74,
    name: "Geodude",
    type: "rock",
    level: 5,
    hp: 40,
    moves: ["Rock Throw", "Tackle", "Rock Slide"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/74.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/74.png",
  },
  {
    id: 75,
    name: "Graveler",
    type: "rock",
    level: 16,
    hp: 55,
    moves: ["Rock Throw", "Tackle", "Rock Slide", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/75.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/75.png",
  },
  {
    id: 76,
    name: "Golem",
    type: "rock",
    level: 36,
    hp: 80,
    moves: ["Rock Throw", "Tackle", "Rock Slide", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/76.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/76.png",
  },
];

function getWrongAttackQtd() {
  let pokemonLessList = [];
  let pokemonMoreList = [];
  for (let i = 0; i < pokemons.length; i++) {
    if (pokemons[i].moves.length != 4) {
      if (pokemons[i].moves.length < 4) {
        pokemonLessList.push(pokemons[i].name);
      } else {
        pokemonMoreList.push(pokemons[i].name);
      }
    }
  }
  return [pokemonLessList, pokemonMoreList];
}

console.log(
  "Less moves: " +
    getWrongAttackQtd(pokemons)[0] +
    "\nMore moves: " +
    getWrongAttackQtd(pokemons)[1]
);
