export const pokemons = [
  {
    id: 1,
    name: "Bulbasaur",
    type: "grass",
    level: 5,
    hp: 45,
    moves: ["Tackle", "Leech Seed", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/1.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/1.png",
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "grass",
    level: 16,
    hp: 60,
    moves: ["Body Slam", "Double Team", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/2.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/2.png",
  },
  {
    id: 3,
    name: "Venusaur",
    type: "grass",
    level: 36,
    hp: 80,
    moves: ["Body Slam", "Mega Drain", "Razor Leaf", "Solar Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/3.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/3.png",
  },
  {
    id: 4,
    name: "Charmander",
    type: "fire",
    level: 5,
    hp: 39,
    moves: ["Scratch", "Growl", "Ember", "Smokescreen"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/4.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/4.png",
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "fire",
    level: 16,
    hp: 58,
    moves: ["Slash", "Rage", "Ember", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/5.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/5.png",
  },
  {
    id: 6,
    name: "Charizard",
    type: "fire",
    level: 36,
    hp: 78,
    moves: ["Slash", "Fly", "Earthquake", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/6.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/6.png",
  },
  {
    id: 7,
    name: "Squirtle",
    type: "water",
    level: 5,
    hp: 44,
    moves: ["Tackle", "Bite", "Water Gun", "Bubble"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/7.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/7.png",
  },
  {
    id: 8,
    name: "Wartortle",
    type: "water",
    level: 16,
    hp: 59,
    moves: ["Bite", "Skull Bash", "Body Slam", "Bubblebeam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/8.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/8.png",
  },
  {
    id: 9,
    name: "Blastoise",
    type: "water",
    level: 36,
    hp: 79,
    moves: ["Double Edge", "Ice Beam", "Earthquake", "Surf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/9.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/9.png",
  },
  {
    id: 10,
    name: "Caterpie",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Tackle", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/10.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/10.png",
  },
  {
    id: 11,
    name: "Metapod",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/11.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/11.png",
  },
  {
    id: 12,
    name: "Butterfree",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Toxic", "Sleep Powder", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/12.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/12.png",
  },
  {
    id: 13,
    name: "Weedle",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Poison Sting", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/13.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/13.png",
  },
  {
    id: 14,
    name: "Kakuna",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/14.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/14.png",
  },
  {
    id: 15,
    name: "Beedrill",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Fury Attack", "Swords Dance", "Toxic", "Double Edge"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/15.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/15.png",
  },
  {
    id: 16,
    name: "Pidgey",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Gust", "Quick Attack", "Sand Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/16.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/16.png",
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: "normal",
    level: 16,
    hp: 63,
    moves: ["Take Down", "Razor Wind", "Double Team", "Sky Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/17.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/17.png",
  },
  {
    id: 18,
    name: "Pidgeot",
    type: "normal",
    level: 36,
    hp: 83,
    moves: ["Double Edge", "Wing Attack", "Double Team", "Fly"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/18.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/18.png",
  },
];
