export const pokemons = [
  {
    id: 1,
    name: "Bulbasaur",
    type: "grass",
    level: 5,
    hp: 45,
    moves: ["Tackle", "Leech Seed", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/1.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/1.png",
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "grass",
    level: 16,
    hp: 60,
    moves: ["Body Slam", "Double Team", "Vine Whip", "Razor Leaf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/2.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/2.png",
  },
  {
    id: 3,
    name: "Venusaur",
    type: "grass",
    level: 36,
    hp: 80,
    moves: ["Body Slam", "Mega Drain", "Razor Leaf", "Solar Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/3.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/3.png",
  },
  {
    id: 4,
    name: "Charmander",
    type: "fire",
    level: 5,
    hp: 39,
    moves: ["Scratch", "Growl", "Ember", "Smokescreen"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/4.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/4.png",
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "fire",
    level: 16,
    hp: 58,
    moves: ["Slash", "Rage", "Ember", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/5.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/5.png",
  },
  {
    id: 6,
    name: "Charizard",
    type: "fire",
    level: 36,
    hp: 78,
    moves: ["Slash", "Fly", "Earthquake", "Flamethrower"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/6.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/6.png",
  },
  {
    id: 7,
    name: "Squirtle",
    type: "water",
    level: 5,
    hp: 44,
    moves: ["Tackle", "Bite", "Water Gun", "Bubble"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/7.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/7.png",
  },
  {
    id: 8,
    name: "Wartortle",
    type: "water",
    level: 16,
    hp: 59,
    moves: ["Bite", "Skull Bash", "Body Slam", "Bubblebeam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/8.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/8.png",
  },
  {
    id: 9,
    name: "Blastoise",
    type: "water",
    level: 36,
    hp: 79,
    moves: ["Double Edge", "Ice Beam", "Earthquake", "Surf"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/9.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/9.png",
  },
  {
    id: 10,
    name: "Caterpie",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Tackle", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/10.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/10.png",
  },
  {
    id: 11,
    name: "Metapod",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/11.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/11.png",
  },
  {
    id: 12,
    name: "Butterfree",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Toxic", "Sleep Powder", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/12.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/12.png",
  },
  {
    id: 13,
    name: "Weedle",
    type: "bug",
    level: 5,
    hp: 45,
    moves: ["Poison Sting", "String Shot"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/13.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/13.png",
  },
  {
    id: 14,
    name: "Kakuna",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/14.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/14.png",
  },
  {
    id: 15,
    name: "Beedrill",
    type: "bug",
    level: 36,
    hp: 80,
    moves: ["Fury Attack", "Swords Dance", "Toxic", "Double Edge"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/15.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/15.png",
  },
  {
    id: 16,
    name: "Pidgey",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Gust", "Quick Attack", "Sand Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/16.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/16.png",
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: "normal",
    level: 16,
    hp: 63,
    moves: ["Take Down", "Razor Wind", "Double Team", "Sky Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/17.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/17.png",
  },
  {
    id: 18,
    name: "Pidgeot",
    type: "normal",
    level: 36,
    hp: 83,
    moves: ["Double Edge", "Wing Attack", "Double Team", "Fly"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/18.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/18.png",
  },

  {
    id: 19,
    name: "Rattata",
    type: "normal",
    level: 5,
    hp: 30,
    moves: ["Tackle", "Quick Attack", "Focus Energy"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/19.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/19.png",
  },
  {
    id: 20,
    name: "Raticate",
    type: "normal",
    level: 16,
    hp: 55,
    moves: ["Bite", "Hyper Fang", "Quick Attack", "Focus Energy"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/20.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/20.png",
  },
  {
    id: 21,
    name: "Spearow",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Gust", "Peck", "Quick Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/21.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/21.png",
  },
  {
    id: 22,
    name: "Fearow",
    type: "normal",
    level: 16,
    hp: 65,
    moves: ["Drill Peck", "Aerial Ace", "Quick Attack", "Whirlwind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/22.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/22.png",
  },
  {
    id: 23,
    name: "Ekans",
    type: "poison",
    level: 5,
    hp: 35,
    moves: ["Poison Sting", "Wrap", "Acid"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/23.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/23.png",
  },
  {
    id: 24,
    name: "Arbok",
    type: "poison",
    level: 16,
    hp: 60,
    moves: ["Bite", "Wrap", "Acid", "Glare"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/24.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/24.png",
  },
  {
    id: 25,
    name: "Pikachu",
    type: "electric",
    level: 5,
    hp: 35,
    moves: ["Thunder Shock", "Quick Attack", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/25.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/25.png",
  },
  {
    id: 26,
    name: "Raichu",
    type: "electric",
    level: 16,
    hp: 60,
    moves: ["Thunder Shock", "Quick Attack", "Thunder", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/26.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/26.png",
  },
  {
    id: 27,
    name: "Sandshrew",
    type: "ground",
    level: 5,
    hp: 50,
    moves: ["Scratch", "Sand Attack", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/27.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/27.png",
  },
  {
    id: 28,
    name: "Sandslash",
    type: "ground",
    level: 16,
    hp: 75,
    moves: ["Scratch", "Sand Attack", "Slash", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/28.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/28.png",
  },
  {
    id: 29,
    name: "Nidoran♀",
    type: "poison",
    level: 5,
    hp: 55,
    moves: ["Poison Sting", "Scratch", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/29.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/29.png",
  },
  {
    id: 30,
    name: "Nidorina",
    type: "poison",
    level: 16,
    hp: 70,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/30.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/30.png",
  },
  {
    id: 31,
    name: "Nidoqueen",
    type: "poison",
    level: 36,
    hp: 90,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/31.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/31.png",
  },
  {
    id: 32,
    name: "Nidoran♂",
    type: "poison",
    level: 5,
    hp: 46,
    moves: ["Poison Sting", "Scratch", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/32.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/32.png",
  },
  {
    id: 33,
    name: "Nidorino",
    type: "poison",
    level: 16,
    hp: 61,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/33.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/33.png",
  },
  {
    id: 34,
    name: "Nidoking",
    type: "poison",
    level: 36,
    hp: 81,
    moves: ["Poison Sting", "Scratch", "Tackle", "Harden", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/34.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/34.png",
  },
  {
    id: 35,
    name: "Clefairy",
    type: "fairy",
    level: 5,
    hp: 70,
    moves: ["Pound", "Sing", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/35.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/35.png",
  },
  {
    id: 36,
    name: "Clefable",
    type: "fairy",
    level: 16,
    hp: 95,
    moves: ["Pound", "Sing", "Defense Curl", "Moonblast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/36.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/36.png",
  },
  {
    id: 37,
    name: "Vulpix",
    type: "fire",
    level: 5,
    hp: 38,
    moves: ["Ember", "Quick Attack", "Tail Whip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/37.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/37.png",
  },
  {
    id: 38,
    name: "Ninetales",
    type: "fire",
    level: 16,
    hp: 73,
    moves: ["Ember", "Quick Attack", "Tail Whip", "Fire Blast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/38.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/38.png",
  },
  {
    id: 39,
    name: "Jigglypuff",
    type: "normal",
    level: 5,
    hp: 115,
    moves: ["Pound", "Sing", "Defense Curl"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/39.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/39.png",
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: "normal",
    level: 16,
    hp: 140,
    moves: ["Pound", "Sing", "Defense Curl", "Dazzling Gleam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/40.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/40.png",
  },
  {
    id: 41,
    name: "Zubat",
    type: "poison",
    level: 5,
    hp: 40,
    moves: ["Bite", "Leer", "Quick Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/41.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/41.png",
  },
  {
    id: 42,
    name: "Golbat",
    type: "poison",
    level: 16,
    hp: 75,
    moves: ["Bite", "Leer", "Quick Attack", "Wing Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/42.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/42.png",
  },
  {
    id: 43,
    name: "Oddish",
    type: "grass",
    level: 5,
    hp: 45,
    moves: ["Absorb", "Poison Powder", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/43.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/43.png",
  },
  {
    id: 44,
    name: "Gloom",
    type: "grass",
    level: 16,
    hp: 60,
    moves: ["Absorb", "Poison Powder", "Sleep Powder", "Acid"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/44.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/44.png",
  },
  {
    id: 45,
    name: "Vileplume",
    type: "grass",
    level: 36,
    hp: 75,
    moves: ["Poison Powder", "Sleep Powder", "Acid", "Petal Dance"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/45.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/45.png",
  },
  {
    id: 46,
    name: "Paras",
    type: "bug",
    level: 5,
    hp: 35,
    moves: ["Scratch", "Stun Spore", "Poison Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/46.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/46.png",
  },
  {
    id: 47,
    name: "Parasect",
    type: "bug",
    level: 16,
    hp: 60,
    moves: ["Stun Spore", "Poison Powder", "Fury Cutter"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/47.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/47.png",
  },
  {
    id: 48,
    name: "Venonat",
    type: "bug",
    level: 5,
    hp: 60,
    moves: ["Confusion", "Poison Powder", "Stun Spore"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/48.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/48.png",
  },
  {
    id: 49,
    name: "Venomoth",
    type: "bug",
    level: 16,
    hp: 70,
    moves: ["Confusion", "Poison Powder", "Stun Spore", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/49.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/49.png",
  },
  {
    id: 50,
    name: "Diglett",
    type: "ground",
    level: 5,
    hp: 10,
    moves: ["Scratch", "Sand Attack", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/50.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/50.png",
  },
  {
    id: 51,
    name: "Dugtrio",
    type: "ground",
    level: 16,
    hp: 35,
    moves: ["Mud Slap", "Sand Attack", "Mud Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/51.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/51.png",
  },
  {
    id: 52,
    name: "Meowth",
    type: "normal",
    level: 5,
    hp: 40,
    moves: ["Scratch", "Bite", "Quick Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/52.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/52.png",
  },
  {
    id: 53,
    name: "Persian",
    type: "normal",
    level: 16,
    hp: 65,
    moves: ["Scratch", "Bite", "Quick Attack", "Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/53.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/53.png",
  },
  {
    id: 54,
    name: "Psyduck",
    type: "water",
    level: 5,
    hp: 50,
    moves: ["Scratch", "Water Gun", "Zen Headbutt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/54.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/54.png",
  },
  {
    id: 55,
    name: "Golduck",
    type: "water",
    level: 16,
    hp: 80,
    moves: ["Scratch", "Water Gun", "Zen Headbutt", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/55.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/55.png",
  },
  {
    id: 56,
    name: "Mankey",
    type: "fighting",
    level: 5,
    hp: 40,
    moves: ["Scratch", "Low Kick", "Karate Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/56.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/56.png",
  },
  {
    id: 57,
    name: "Primeape",
    type: "fighting",
    level: 16,
    hp: 65,
    moves: ["Scratch", "Low Kick", "Karate Chop", "Cross Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/57.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/57.png",
  },
  {
    id: 58,
    name: "Growlithe",
    type: "fire",
    level: 5,
    hp: 55,
    moves: ["Bite", "Ember", "Odor Sleuth"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/58.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/58.png",
  },
  {
    id: 59,
    name: "Arcanine",
    type: "fire",
    level: 16,
    hp: 90,
    moves: ["Bite", "Ember", "Odor Sleuth", "Fire Fang"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/59.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/59.png",
  },
  {
    id: 60,
    name: "Poliwag",
    type: "water",
    level: 5,
    hp: 40,
    moves: ["Bubble", "Water Gun", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/60.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/60.png",
  },
  {
    id: 61,
    name: "Poliwhirl",
    type: "water",
    level: 16,
    hp: 65,
    moves: ["Bubble", "Water Gun", "Mud Slap", "Bubble Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/61.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/61.png",
  },
  {
    id: 62,
    name: "Poliwrath",
    type: "water",
    level: 36,
    hp: 90,
    moves: ["Water Gun", "Mud Slap", "Bubble Beam", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/62.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/62.png",
  },
  {
    id: 63,
    name: "Abra",
    type: "psychic",
    level: 5,
    hp: 25,
    moves: ["Teleport", "Zen Headbutt", "Confusion"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/63.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/63.png",
  },
  {
    id: 64,
    name: "Kadabra",
    type: "psychic",
    level: 16,
    hp: 40,
    moves: ["Teleport", "Zen Headbutt", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/64.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/64.png",
  },
  {
    id: 65,
    name: "Alakazam",
    type: "psychic",
    level: 36,
    hp: 55,
    moves: ["Teleport", "Zen Headbutt", "Confusion", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/65.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/65.png",
  },
  {
    id: 66,
    name: "Machop",
    type: "fighting",
    level: 5,
    hp: 40,
    moves: ["Low Kick", "Karate Chop", "Cross Chop"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/66.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/66.png",
  },
  {
    id: 67,
    name: "Machoke",
    type: "fighting",
    level: 16,
    hp: 65,
    moves: ["Low Kick", "Karate Chop", "Cross Chop", "Submission"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/67.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/67.png",
  },
  {
    id: 68,
    name: "Machamp",
    type: "fighting",
    level: 36,
    hp: 90,
    moves: ["Low Kick", "Karate Chop", "Cross Chop", "Submission"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/68.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/68.png",
  },
  {
    id: 69,
    name: "Bellsprout",
    type: "grass",
    level: 5,
    hp: 50,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/69.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/69.png",
  },
  {
    id: 70,
    name: "Weepinbell",
    type: "grass",
    level: 16,
    hp: 65,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder", "Seed Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/70.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/70.png",
  },
  {
    id: 71,
    name: "Victreebel",
    type: "grass",
    level: 36,
    hp: 80,
    moves: ["Vine Whip", "Poison Powder", "Sleep Powder", "Seed Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/71.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/71.png",
  },
  {
    id: 72,
    name: "Tentacool",
    type: "water",
    level: 5,
    hp: 40,
    moves: ["Bubble", "Poison Sting", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/72.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/72.png",
  },
  {
    id: 73,
    name: "Tentacruel",
    type: "water",
    level: 16,
    hp: 80,
    moves: ["Bubble", "Poison Sting", "Water Gun", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/73.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/73.png",
  },
  {
    id: 74,
    name: "Geodude",
    type: "rock",
    level: 5,
    hp: 40,
    moves: ["Rock Throw", "Tackle", "Rock Slide"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/74.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/74.png",
  },
  {
    id: 75,
    name: "Graveler",
    type: "rock",
    level: 16,
    hp: 55,
    moves: ["Rock Throw", "Tackle", "Rock Slide", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/75.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/75.png",
  },
  {
    id: 76,
    name: "Golem",
    type: "rock",
    level: 36,
    hp: 80,
    moves: ["Rock Throw", "Tackle", "Rock Slide", "Mud Slap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/76.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/76.png",
  },
  {
    id: 77,
    name: "Ponyta",
    type: "fire",
    level: 5,
    hp: 50,
    moves: ["Ember", "Stomp", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/77.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/77.png",
  },
  {
    id: 78,
    name: "Rapidash",
    type: "fire",
    level: 16,
    hp: 65,
    moves: ["Ember", "Stomp", "Tackle", "Fire Spin"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/78.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/78.png",
  },
  {
    id: 79,
    name: "Slowpoke",
    type: "water",
    level: 5,
    hp: 65,
    moves: ["Water Gun", "Confusion", "Headbutt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/79.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/79.png",
  },
  {
    id: 80,
    name: "Slowbro",
    type: "water",
    level: 16,
    hp: 95,
    moves: ["Water Gun", "Confusion", "Headbutt", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/80.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/80.png",
  },
  {
    id: 81,
    name: "Magnemite",
    type: "electric",
    level: 5,
    hp: 25,
    moves: ["Tackle", "Spark", "Thunder Shock"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/81.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/81.png",
  },
  {
    id: 82,
    name: "Magneton",
    type: "electric",
    level: 16,
    hp: 50,
    moves: ["Tackle", "Spark", "Thunder Shock", "Thunder Wave"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/82.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/82.png",
  },
  {
    id: 83,
    name: "Farfetch'd",
    type: "normal",
    level: 5,
    hp: 52,
    moves: ["Peck", "Leer", "Fury Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/83.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/83.png",
  },
  {
    id: 84,
    name: "Doduo",
    type: "normal",
    level: 5,
    hp: 35,
    moves: ["Peck", "Leer", "Fury Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/84.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/84.png",
  },
  {
    id: 85,
    name: "Dodrio",
    type: "normal",
    level: 16,
    hp: 60,
    moves: ["Peck", "Leer", "Fury Attack", "Tri Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/85.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/85.png",
  },
  {
    id: 86,
    name: "Seel",
    type: "water",
    level: 5,
    hp: 65,
    moves: ["Headbutt", "Ice Shard", "Aurora Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/86.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/86.png",
  },
  {
    id: 87,
    name: "Dewgong",
    type: "water",
    level: 16,
    hp: 90,
    moves: ["Headbutt", "Ice Shard", "Aurora Beam", "Icy Wind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/87.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/87.png",
  },
  {
    id: 88,
    name: "Grimer",
    type: "poison",
    level: 5,
    hp: 80,
    moves: ["Mud Slap", "Poison Sting", "Acid"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/88.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/88.png",
  },
  {
    id: 89,
    name: "Muk",
    type: "poison",
    level: 16,
    hp: 105,
    moves: ["Mud Slap", "Poison Sting", "Acid", "Sludge"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/89.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/89.png",
  },
  {
    id: 90,
    name: "Shellder",
    type: "water",
    level: 5,
    hp: 30,
    moves: ["Tackle", "Withdraw", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/90.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/90.png",
  },
  {
    id: 91,
    name: "Cloyster",
    type: "water",
    level: 16,
    hp: 50,
    moves: ["Tackle", "Withdraw", "Water Gun", "Icy Wind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/91.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/91.png",
  },
  {
    id: 92,
    name: "Gastly",
    type: "ghost",
    level: 5,
    hp: 30,
    moves: ["Lick", "Sucker Punch", "Hypnosis"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/92.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/92.png",
  },
  {
    id: 93,
    name: "Haunter",
    type: "ghost",
    level: 16,
    hp: 45,
    moves: ["Lick", "Sucker Punch", "Hypnosis", "Night Shade"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/93.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/93.png",
  },
  {
    id: 94,
    name: "Gengar",
    type: "ghost",
    level: 16,
    hp: 60,
    moves: ["Lick", "Sucker Punch", "Hypnosis", "Night Shade", "Shadow Ball"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/94.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/94.png",
  },
  {
    id: 95,
    name: "Onix",
    type: "rock",
    level: 5,
    hp: 35,
    moves: ["Tackle", "Rock Throw", "Bind"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/95.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/95.png",
  },
  {
    id: 96,
    name: "Drowzee",
    type: "psychic",
    level: 5,
    hp: 60,
    moves: ["Pound", "Confusion", "Headbutt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/96.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/96.png",
  },
  {
    id: 97,
    name: "Hypno",
    type: "psychic",
    level: 16,
    hp: 85,
    moves: ["Pound", "Confusion", "Headbutt", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/97.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/97.png",
  },
  {
    id: 98,
    name: "Krabby",
    type: "water",
    level: 5,
    hp: 30,
    moves: ["Bubble", "Mud Shot", "Vicegrip"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/98.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/98.png",
  },
  {
    id: 99,
    name: "Kingler",
    type: "water",
    level: 16,
    hp: 55,
    moves: ["Bubble", "Mud Shot", "Vicegrip", "Megahorn"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/99.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/99.png",
  },
  {
    id: 100,
    name: "Voltorb",
    type: "electric",
    level: 5,
    hp: 40,
    moves: ["Tackle", "Spark", "Swift"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/100.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/100.png",
  },
  {
    id: 101,
    name: "Electrode",
    type: "electric",
    level: 16,
    hp: 60,
    moves: ["Tackle", "Spark", "Swift", "Thunderbolt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/101.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/101.png",
  },
  {
    id: 102,
    name: "Exeggcute",
    type: "grass",
    level: 5,
    hp: 60,
    moves: ["Confusion", "Stun Spore", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/102.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/102.png",
  },
  {
    id: 103,
    name: "Exeggutor",
    type: "grass",
    level: 16,
    hp: 95,
    moves: ["Confusion", "Stun Spore", "Sleep Powder", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/103.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/103.png",
  },
  {
    id: 104,
    name: "Cubone",
    type: "ground",
    level: 5,
    hp: 50,
    moves: ["Mud Slap", "Bone Club", "Headbutt"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/104.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/104.png",
  },
  {
    id: 105,
    name: "Marowak",
    type: "ground",
    level: 16,
    hp: 60,
    moves: ["Mud Slap", "Bone Club", "Headbutt", "Bone Rush"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/105.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/105.png",
  },
  {
    id: 106,
    name: "Hitmonlee",
    type: "fighting",
    level: 16,
    hp: 50,
    moves: ["Low Kick", "Rock Smash", "Submission", "Low Sweep"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/106.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/106.png",
  },
  {
    id: 107,
    name: "Hitmonchan",
    type: "fighting",
    level: 16,
    hp: 50,
    moves: ["Brick Break", "Fire Punch", "Ice Punch", "Thunder Punch"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/107.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/107.png",
  },
  {
    id: 108,
    name: "Lickitung",
    type: "normal",
    level: 16,
    hp: 90,
    moves: ["Lick", "Stomp", "Hyper Beam", "Wrap"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/108.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/108.png",
  },
  {
    id: 109,
    name: "Koffing",
    type: "poison",
    level: 5,
    hp: 40,
    moves: ["Smog", "Tackle", "Toxic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/109.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/109.png",
  },
  {
    id: 110,
    name: "Weezing",
    type: "poison",
    level: 16,
    hp: 65,
    moves: ["Smog", "Tackle", "Toxic", "Sludge Bomb"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/110.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/110.png",
  },
  {
    id: 111,
    name: "Rhyhorn",
    type: "ground",
    level: 5,
    hp: 80,
    moves: ["Mud Slap", "Rock Throw", "Horn Attack"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/111.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/111.png",
  },
  {
    id: 112,
    name: "Rhydon",
    type: "ground",
    level: 16,
    hp: 105,
    moves: ["Mud Slap", "Rock Throw", "Horn Attack", "Earthquake"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/112.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/112.png",
  },
  {
    id: 113,
    name: "Chansey",
    type: "normal",
    level: 16,
    hp: 250,
    moves: ["Softboiled", "Egg Bomb", "Doubleslap", "Dazzling Gleam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/113.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/113.png",
  },
  {
    id: 114,
    name: "Tangela",
    type: "grass",
    level: 16,
    hp: 65,
    moves: ["Vine Whip", "Constrict", "Poison Powder", "Sleep Powder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/114.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/114.png",
  },
  {
    id: 115,
    name: "Kangaskhan",
    type: "normal",
    level: 16,
    hp: 105,
    moves: ["Mud Slap", "Return", "Brick Break", "Double-Edge"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/115.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/115.png",
  },
  {
    id: 116,
    name: "Horsea",
    type: "water",
    level: 5,
    hp: 30,
    moves: ["Bubble", "Water Gun", "Bubblebeam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/116.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/116.png",
  },
  {
    id: 117,
    name: "Seadra",
    type: "water",
    level: 16,
    hp: 55,
    moves: ["Bubble", "Water Gun", "Bubblebeam", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/117.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/117.png",
  },
  {
    id: 118,
    name: "Goldeen",
    type: "water",
    level: 5,
    hp: 45,
    moves: ["Peck", "Horn Attack", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/118.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/118.png",
  },
  {
    id: 119,
    name: "Seaking",
    type: "water",
    level: 16,
    hp: 80,
    moves: ["Peck", "Horn Attack", "Water Gun", "Megahorn"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/119.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/119.png",
  },
  {
    id: 120,
    name: "Staryu",
    type: "water",
    level: 5,
    hp: 30,
    moves: ["Water Gun", "Twister", "Bubblebeam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/120.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/120.png",
  },
  {
    id: 121,
    name: "Starmie",
    type: "water",
    level: 16,
    hp: 60,
    moves: ["Water Gun", "Twister", "Bubblebeam", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/121.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/121.png",
  },
  {
    id: 122,
    name: "Mr. Mime",
    type: "psychic",
    level: 16,
    hp: 80,
    moves: ["Confusion", "Psychic", "Psybeam", "Psychic"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/122.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/122.png",
  },
  {
    id: 123,
    name: "Scyther",
    type: "bug",
    level: 16,
    hp: 70,
    moves: ["Fury Cutter", "Bug Buzz", "Agility", "Night Slash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/123.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/123.png",
  },
  {
    id: 124,
    name: "Jynx",
    type: "ice",
    level: 16,
    hp: 65,
    moves: ["Frost Breath", "Powder Snow", "Ice Punch", "Blizzard"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/124.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/124.png",
  },
  {
    id: 125,
    name: "Electabuzz",
    type: "electric",
    level: 16,
    hp: 65,
    moves: ["Low Kick", "Thunder Punch", "Thunder Shock", "Thunder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/125.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/125.png",
  },
  {
    id: 126,
    name: "Magmar",
    type: "fire",
    level: 16,
    hp: 65,
    moves: ["Ember", "Fire Punch", "Smog", "Fire Blast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/126.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/126.png",
  },
  {
    id: 127,
    name: "Pinsir",
    type: "bug",
    level: 16,
    hp: 65,
    moves: ["Vicegrip", "X-Scissor", "Aerial Ace", "Submission"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/127.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/127.png",
  },
  {
    id: 128,
    name: "Tauros",
    type: "normal",
    level: 16,
    hp: 75,
    moves: ["Horn Attack", "Stomp", "Body Slam", "Earthquake"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/128.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/128.png",
  },
  {
    id: 129,
    name: "Magikarp",
    type: "water",
    level: 5,
    hp: 20,
    moves: ["Splash"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/129.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/129.png",
  },
  {
    id: 130,
    name: "Gyarados",
    type: "water",
    level: 16,
    hp: 95,
    moves: ["Bite", "Dragon Rage", "Hydro Pump", "Dragon Pulse"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/130.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/130.png",
  },
  {
    id: 131,
    name: "Lapras",
    type: "water",
    level: 16,
    hp: 130,
    moves: ["Water Gun", "Ice Beam", "Blizzard", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/131.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/131.png",
  },
  {
    id: 132,
    name: "Ditto",
    type: "normal",
    level: 16,
    hp: 48,
    moves: ["Transform"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/132.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/132.png",
  },
  {
    id: 133,
    name: "Eevee",
    type: "normal",
    level: 5,
    hp: 55,
    moves: ["Quick Attack", "Bite", "Tackle"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/133.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/133.png",
  },
  {
    id: 134,
    name: "Vaporeon",
    type: "water",
    level: 16,
    hp: 130,
    moves: ["Water Gun", "Ice Beam", "Blizzard", "Hydro Pump"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/134.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/134.png",
  },
  {
    id: 135,
    name: "Jolteon",
    type: "electric",
    level: 16,
    hp: 65,
    moves: ["Thunder Shock", "Thunder Punch", "Thunder Wave", "Thunder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/135.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/135.png",
  },
  {
    id: 136,
    name: "Flareon",
    type: "fire",
    level: 16,
    hp: 65,
    moves: ["Ember", "Fire Punch", "Smog", "Fire Blast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/136.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/136.png",
  },
  {
    id: 137,
    name: "Porygon",
    type: "normal",
    level: 16,
    hp: 65,
    moves: ["Tri Attack", "Psybeam", "Thunder Punch", "Thunder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/137.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/137.png",
  },
  {
    id: 138,
    name: "Omanyte",
    type: "rock",
    level: 5,
    hp: 35,
    moves: ["Tackle", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/138.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/138.png",
  },
  {
    id: 139,
    name: "Omastar",
    type: "rock",
    level: 16,
    hp: 70,
    moves: ["Mud Shot", "Ancient Power", "Water Gun", "Ancient Power"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/139.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/139.png",
  },
  {
    id: 140,
    name: "Kabuto",
    type: "rock",
    level: 5,
    hp: 30,
    moves: ["Tackle", "Water Gun"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/140.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/140.png",
  },
  {
    id: 141,
    name: "Kabutops",
    type: "rock",
    level: 16,
    hp: 60,
    moves: ["Mud Shot", "Ancient Power", "Water Gun", "Ancient Power"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/141.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/141.png",
  },
  {
    id: 142,
    name: "Aerodactyl",
    type: "rock",
    level: 16,
    hp: 80,
    moves: ["Bite", "Ancient Power", "Water Gun", "Ancient Power"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/142.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/142.png",
  },
  {
    id: 143,
    name: "Snorlax",
    type: "normal",
    level: 16,
    hp: 160,
    moves: ["Lick", "Body Slam", "Hyper Beam", "Hyper Beam"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/143.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/143.png",
  },
  {
    id: 144,
    name: "Articuno",
    type: "ice",
    level: 16,
    hp: 90,
    moves: ["Ice Beam", "Blizzard", "Ancient Power", "Ancient Power"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/144.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/144.png",
  },
  {
    id: 145,
    name: "Zapdos",
    type: "electric",
    level: 16,
    hp: 90,
    moves: ["Thunder Shock", "Thunder Punch", "Thunder Wave", "Thunder"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/145.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/145.png",
  },
  {
    id: 146,
    name: "Moltres",
    type: "fire",
    level: 16,
    hp: 90,
    moves: ["Ember", "Fire Punch", "Smog", "Fire Blast"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/146.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/146.png",
  },
  {
    id: 147,
    name: "Dratini",
    type: "dragon",
    level: 5,
    hp: 41,
    moves: ["Tackle", "Dragon Breath"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/147.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/147.png",
  },
  {
    id: 148,
    name: "Dragonair",
    type: "dragon",
    level: 16,
    hp: 61,
    moves: ["Dragon Breath", "Dragon Pulse", "Dragon Rage", "Dragon Dance"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/148.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/148.png",
  },
  {
    id: 149,
    name: "Dragonite",
    type: "dragon",
    level: 16,
    hp: 91,
    moves: ["Dragon Pulse", "Dragon Rage", "Dragon Dance", "Dragon Claw"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/149.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/149.png",
  },
  {
    id: 150,
    name: "Mewtwo",
    type: "psychic",
    level: 16,
    hp: 106,
    moves: ["Psychic", "Shadow Ball", "Psycho Cut", "Recover"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/150.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/150.png",
  },
  {
    id: 151,
    name: "Mew",
    type: "psychic",
    level: 16,
    hp: 100,
    moves: ["Psychic", "Recover", "Psycho Cut", "Shadow Ball"],
    sprite: "sprites/pokemon/main-sprites/firered-leafgreen/151.png",
    image: "sprites/pokemon/main-sprites/battle_sprites/151.png",
  },
];

function getWrongAttackQtd() {
  let pokemonLessList = [];
  let pokemonMoreList = [];
  for (let i = 0; i < pokemons.length; i++) {
    if (pokemons[i].moves.length != 4) {
      if (pokemons[i].moves.length < 4) {
        pokemonLessList.push(pokemons[i].name);
      } else {
        pokemonMoreList.push(pokemons[i].name);
      }
    }
  }
  return [pokemonLessList, pokemonMoreList];
}

console.log(
  "Less moves: " +
    getWrongAttackQtd(pokemons)[0] +
    "\nMore moves: " +
    getWrongAttackQtd(pokemons)[1]
);
